// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://rrl360.com/index.html",
        "contact": {
            "name": "伍晓飞",
            "email": "wuxiaofei@rechaintech.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/pub/coin_price/{coin}/{vs_coin}": {
            "get": {
                "description": "获取币价换算，多节点签名版",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "default"
                ],
                "summary": "获取币价换算，多节点签名版",
                "operationId": "CoinPriceSignHandler",
                "parameters": [
                    {
                        "enum": [
                            "btc",
                            "aed",
                            "ars",
                            "aud",
                            "bch",
                            "bdt",
                            "bhd",
                            "bits",
                            "bmd",
                            "bnb",
                            "brl",
                            "byn",
                            "cad",
                            "chf",
                            "clp",
                            "cny",
                            "czk",
                            "dkk",
                            "dot",
                            "eos",
                            "eth",
                            "eur",
                            "gbp",
                            "hkd",
                            "huf",
                            "idr",
                            "ils",
                            "inr",
                            "jpy",
                            "krw",
                            "kwd",
                            "link",
                            "lkr",
                            "ltc",
                            "mmk",
                            "mxn",
                            "myr",
                            "ngn",
                            "nok",
                            "nzd",
                            "php",
                            "pkr",
                            "pln",
                            "rub",
                            "sar",
                            "sats",
                            "sek",
                            "sgd",
                            "thb",
                            "try",
                            "twd",
                            "uah",
                            "usd",
                            "vef",
                            "vnd",
                            "xag",
                            "xau",
                            "xdr",
                            "xlm",
                            "xrp",
                            "yfi",
                            "zar"
                        ],
                        "type": "string",
                        "default": "eth",
                        "description": "目标币价",
                        "name": "coin",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "btc",
                            "aed",
                            "ars",
                            "aud",
                            "bch",
                            "bdt",
                            "bhd",
                            "bits",
                            "bmd",
                            "bnb",
                            "brl",
                            "byn",
                            "cad",
                            "chf",
                            "clp",
                            "cny",
                            "czk",
                            "dkk",
                            "dot",
                            "eos",
                            "eth",
                            "eur",
                            "gbp",
                            "hkd",
                            "huf",
                            "idr",
                            "ils",
                            "inr",
                            "jpy",
                            "krw",
                            "kwd",
                            "link",
                            "lkr",
                            "ltc",
                            "mmk",
                            "mxn",
                            "myr",
                            "ngn",
                            "nok",
                            "nzd",
                            "php",
                            "pkr",
                            "pln",
                            "rub",
                            "sar",
                            "sats",
                            "sek",
                            "sgd",
                            "thb",
                            "try",
                            "twd",
                            "uah",
                            "usd",
                            "vef",
                            "vnd",
                            "xag",
                            "xau",
                            "xdr",
                            "xlm",
                            "xrp",
                            "yfi",
                            "zar"
                        ],
                        "type": "string",
                        "default": "usd",
                        "description": "vs币价",
                        "name": "vs_coin",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1620383144,
                        "description": "unix 秒数",
                        "name": "timestamp",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "CoinPriceView",
                        "schema": {
                            "$ref": "#/definitions/services.CoinPriceView"
                        },
                        "headers": {
                            "sign": {
                                "type": "string",
                                "description": "签名信息"
                            }
                        }
                    },
                    "500": {
                        "description": "失败时，有相应测试日志输出",
                        "schema": {
                            "$ref": "#/definitions/controls.ApiErr"
                        }
                    }
                }
            }
        },
        "/pub/dex/ftx_chart_prices/btc/{count}/{interval}/{timestamp}": {
            "get": {
                "description": "获取杠杆btc代币不同时间区间的价格图表信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "default"
                ],
                "summary": "获取杠杆btc代币不同时间区间的价格图表信息",
                "operationId": "FtxChartPricesHandler",
                "parameters": [
                    {
                        "type": "string",
                        "default": "0x66a0f676479cee1d7373f3dc2e2952778bff5bd6",
                        "description": "token地址",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "获取多少个数据点",
                        "name": "count",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            1,
                            2,
                            3,
                            4,
                            96
                        ],
                        "type": "integer",
                        "description": "数据间隔值,表示多少个15分钟, 如:1表示15分钟间隔 2表示30分钟间隔 3表示45分钟间隔 ,96表示1天间隔 ；",
                        "name": "interval",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1620383144,
                        "description": "当前时间的unix秒数,该字段未使用，仅在云存储上用于标识",
                        "name": "timestamp",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "stock info",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/services.BlockPrice"
                            }
                        },
                        "headers": {
                            "sign": {
                                "type": "string",
                                "description": "签名信息"
                            }
                        }
                    },
                    "500": {
                        "description": "失败时，有相应测试日志输出",
                        "schema": {
                            "$ref": "#/definitions/controls.ApiErr"
                        }
                    }
                }
            }
        },
        "/pub/dex/lp_price/{pair}/{timestamp}": {
            "get": {
                "description": "获取lp价格信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "default"
                ],
                "summary": "获取lp价格信息",
                "operationId": "PairLpPriceSignHandler",
                "parameters": [
                    {
                        "type": "string",
                        "default": "0x21b8065d10f73ee2e260e5b47d3344d3ced7596e",
                        "description": "token地址",
                        "name": "pair",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1620383144,
                        "description": "当前时间的unix秒数,该字段未使用，仅在云存储上用于标识",
                        "name": "timestamp",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "pair price view list",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/services.PriceView"
                            }
                        },
                        "headers": {
                            "sign": {
                                "type": "string",
                                "description": "签名信息"
                            }
                        }
                    },
                    "500": {
                        "description": "失败时，有相应测试日志输出",
                        "schema": {
                            "$ref": "#/definitions/controls.ApiErr"
                        }
                    }
                }
            }
        },
        "/pub/dex/token_chart_prices/{token}/{count}/{interval}/{timestamp}": {
            "get": {
                "description": "获取token不同时间区间的价格图表信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "default"
                ],
                "summary": "获取token不同时间区间的价格图表信息",
                "operationId": "TokenDayPricesHandler",
                "parameters": [
                    {
                        "type": "string",
                        "default": "0x66a0f676479cee1d7373f3dc2e2952778bff5bd6",
                        "description": "token地址",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "获取多少个数据点",
                        "name": "count",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "15minite",
                            "hour",
                            "day",
                            "1w",
                            "1m"
                        ],
                        "type": "string",
                        "default": "day",
                        "description": "数据间隔 15minite hour day 1w(1周) 1m (1月) ",
                        "name": "interval",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1620383144,
                        "description": "当前时间的unix秒数,该字段未使用，仅在云存储上用于标识",
                        "name": "timestamp",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "stock info",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/services.BlockPrice"
                            }
                        },
                        "headers": {
                            "sign": {
                                "type": "string",
                                "description": "签名信息"
                            }
                        }
                    },
                    "500": {
                        "description": "失败时，有相应测试日志输出",
                        "schema": {
                            "$ref": "#/definitions/controls.ApiErr"
                        }
                    }
                }
            }
        },
        "/pub/dex/token_day_datas/{token}/{days}/{timestamp}": {
            "get": {
                "description": "获取token相应天数的统计图表信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "default"
                ],
                "summary": "获取token相应天数的统计图表信息",
                "operationId": "TokenDayDatasHandler",
                "parameters": [
                    {
                        "type": "string",
                        "default": "0x66a0f676479cee1d7373f3dc2e2952778bff5bd6",
                        "description": "token地址",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 14,
                        "description": "获取最近多少天的数据",
                        "name": "days",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1620383144,
                        "description": "当前时间的unix秒数,该字段未使用，仅在云存储上用于标识",
                        "name": "timestamp",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "stock info",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/services.TokenDayData"
                            }
                        },
                        "headers": {
                            "sign": {
                                "type": "string",
                                "description": "签名信息"
                            }
                        }
                    },
                    "500": {
                        "description": "失败时，有相应测试日志输出",
                        "schema": {
                            "$ref": "#/definitions/controls.ApiErr"
                        }
                    }
                }
            }
        },
        "/pub/dex/token_price/{token}/{data_type}/{timestamp}": {
            "get": {
                "description": "获取token价格信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "default"
                ],
                "summary": "获取token价格信息",
                "operationId": "TokenPriceSignHandler",
                "parameters": [
                    {
                        "type": "string",
                        "default": "0x66a0f676479cee1d7373f3dc2e2952778bff5bd6",
                        "description": "token地址",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            1,
                            2
                        ],
                        "type": "integer",
                        "default": 1,
                        "description": "最高最低价１最高　２最低价",
                        "name": "data_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1620383144,
                        "description": "当前时间的unix秒数,该字段未使用，仅在云存储上用于标识",
                        "name": "timestamp",
                        "in": "path"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "调试",
                        "name": "debug",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "token price info",
                        "schema": {
                            "$ref": "#/definitions/services.HLDataPriceView"
                        },
                        "headers": {
                            "sign": {
                                "type": "string",
                                "description": "签名信息"
                            }
                        }
                    },
                    "500": {
                        "description": "失败时，有相应测试日志输出",
                        "schema": {
                            "$ref": "#/definitions/controls.ApiErr"
                        }
                    }
                }
            }
        },
        "/pub/internal/coin_price/{coin}/{vs_coin}": {
            "get": {
                "description": "获取币价换算，内部单节点",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "default"
                ],
                "summary": "获取币价换算，内部单节点",
                "operationId": "CoinPriceHandler",
                "parameters": [
                    {
                        "enum": [
                            "btc",
                            "aed",
                            "ars",
                            "aud",
                            "bch",
                            "bdt",
                            "bhd",
                            "bits",
                            "bmd",
                            "bnb",
                            "brl",
                            "byn",
                            "cad",
                            "chf",
                            "clp",
                            "cny",
                            "czk",
                            "dkk",
                            "dot",
                            "eos",
                            "eth",
                            "eur",
                            "gbp",
                            "hkd",
                            "huf",
                            "idr",
                            "ils",
                            "inr",
                            "jpy",
                            "krw",
                            "kwd",
                            "link",
                            "lkr",
                            "ltc",
                            "mmk",
                            "mxn",
                            "myr",
                            "ngn",
                            "nok",
                            "nzd",
                            "php",
                            "pkr",
                            "pln",
                            "rub",
                            "sar",
                            "sats",
                            "sek",
                            "sgd",
                            "thb",
                            "try",
                            "twd",
                            "uah",
                            "usd",
                            "vef",
                            "vnd",
                            "xag",
                            "xau",
                            "xdr",
                            "xlm",
                            "xrp",
                            "yfi",
                            "zar"
                        ],
                        "type": "string",
                        "default": "eth",
                        "description": "目标币价",
                        "name": "coin",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "btc",
                            "aed",
                            "ars",
                            "aud",
                            "bch",
                            "bdt",
                            "bhd",
                            "bits",
                            "bmd",
                            "bnb",
                            "brl",
                            "byn",
                            "cad",
                            "chf",
                            "clp",
                            "cny",
                            "czk",
                            "dkk",
                            "dot",
                            "eos",
                            "eth",
                            "eur",
                            "gbp",
                            "hkd",
                            "huf",
                            "idr",
                            "ils",
                            "inr",
                            "jpy",
                            "krw",
                            "kwd",
                            "link",
                            "lkr",
                            "ltc",
                            "mmk",
                            "mxn",
                            "myr",
                            "ngn",
                            "nok",
                            "nzd",
                            "php",
                            "pkr",
                            "pln",
                            "rub",
                            "sar",
                            "sats",
                            "sek",
                            "sgd",
                            "thb",
                            "try",
                            "twd",
                            "uah",
                            "usd",
                            "vef",
                            "vnd",
                            "xag",
                            "xau",
                            "xdr",
                            "xlm",
                            "xrp",
                            "yfi",
                            "zar"
                        ],
                        "type": "string",
                        "default": "usd",
                        "description": "vs币价",
                        "name": "vs_coin",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1620383144,
                        "description": "unix 秒数",
                        "name": "timestamp",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Coin Price",
                        "schema": {
                            "$ref": "#/definitions/services.CoinPriceView"
                        },
                        "headers": {
                            "sign": {
                                "type": "string",
                                "description": "签名信息"
                            }
                        }
                    },
                    "500": {
                        "description": "失败时，有相应测试日志输出",
                        "schema": {
                            "$ref": "#/definitions/controls.ApiErr"
                        }
                    }
                }
            }
        },
        "/pub/internal/dex/lp_price/{pair}/{timestamp}": {
            "get": {
                "description": "内部单节点获取lp价格信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "default"
                ],
                "summary": "获取lp价格信息,内部单节点:",
                "operationId": "PairLpPriceHandler",
                "parameters": [
                    {
                        "type": "string",
                        "default": "0x21b8065d10f73ee2e260e5b47d3344d3ced7596e",
                        "description": "pair地址",
                        "name": "pair",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1620383144,
                        "description": "当前时间的unix秒数,该字段未使用，仅在云存储上用于标识",
                        "name": "timestamp",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "price vew",
                        "schema": {
                            "$ref": "#/definitions/services.PriceView"
                        },
                        "headers": {
                            "sign": {
                                "type": "string",
                                "description": "签名信息"
                            }
                        }
                    },
                    "500": {
                        "description": "失败时，有相应测试日志输出",
                        "schema": {
                            "$ref": "#/definitions/controls.ApiErr"
                        }
                    }
                }
            }
        },
        "/pub/internal/dex/token_info/{token}/{timestamp}": {
            "get": {
                "description": "内部单节点获取token信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "default"
                ],
                "summary": "获取token信息,内部单节点",
                "operationId": "TokenInfoHandler",
                "parameters": [
                    {
                        "type": "string",
                        "default": "0x66a0f676479cee1d7373f3dc2e2952778bff5bd6",
                        "description": "token地址",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1620383144,
                        "description": "当前时间的unix秒数,该字段未使用，仅在云存储上用于标识",
                        "name": "timestamp",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "stock info",
                        "schema": {
                            "$ref": "#/definitions/services.TokenInfo"
                        },
                        "headers": {
                            "sign": {
                                "type": "string",
                                "description": "签名信息"
                            }
                        }
                    },
                    "500": {
                        "description": "失败时，有相应测试日志输出",
                        "schema": {
                            "$ref": "#/definitions/controls.ApiErr"
                        }
                    }
                }
            }
        },
        "/pub/internal/dex/token_price/{token}/{timestamp}": {
            "get": {
                "description": "内部单节点获取token信息,含pair的lp Token内容",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "default"
                ],
                "summary": "获取token价格信息,内部单节点",
                "operationId": "TokenPriceHandler",
                "parameters": [
                    {
                        "type": "string",
                        "default": "0x66a0f676479cee1d7373f3dc2e2952778bff5bd6",
                        "description": "token地址",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            1,
                            2
                        ],
                        "type": "integer",
                        "default": 1,
                        "description": "最高最低价１最高　２最低价",
                        "name": "data_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1620383144,
                        "description": "当前时间的unix秒数,该字段未使用，仅在云存储上用于标识",
                        "name": "timestamp",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Price View",
                        "schema": {
                            "$ref": "#/definitions/services.HLPriceView"
                        },
                        "headers": {
                            "sign": {
                                "type": "string",
                                "description": "签名信息"
                            }
                        }
                    },
                    "500": {
                        "description": "失败时，有相应测试日志输出",
                        "schema": {
                            "$ref": "#/definitions/controls.ApiErr"
                        }
                    }
                }
            }
        },
        "/pub/internal/ftx_price/btc": {
            "get": {
                "description": "获取btc杠杆币价格，内部单节点模式",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "default"
                ],
                "summary": "获取btc杠杆币价格，内部单节点模式",
                "operationId": "FtxPriceHandler",
                "parameters": [
                    {
                        "type": "string",
                        "default": "btc",
                        "description": "btc币价",
                        "name": "coin",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1620383144,
                        "description": "unix 秒数",
                        "name": "timestamp",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Coin Price",
                        "schema": {
                            "$ref": "#/definitions/services.CoinPriceView"
                        },
                        "headers": {
                            "sign": {
                                "type": "string",
                                "description": "签名信息"
                            }
                        }
                    },
                    "500": {
                        "description": "失败时，有相应测试日志输出",
                        "schema": {
                            "$ref": "#/definitions/controls.ApiErr"
                        }
                    }
                }
            }
        },
        "/pub/internal/stock_avgprice": {
            "post": {
                "description": "获取股票平均价格共识 苹果代码  AAPL  ,苹果代码 TSLA",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "default"
                ],
                "summary": "获取股票平均价格共识:",
                "operationId": "StockAvgPriceHandler",
                "parameters": [
                    {
                        "description": "节点价格列表",
                        "name": "nodePrices",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/services.StockNode"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "stock info",
                        "schema": {
                            "$ref": "#/definitions/services.StockNode"
                        },
                        "headers": {
                            "sign": {
                                "type": "string",
                                "description": "签名信息"
                            }
                        }
                    },
                    "500": {
                        "description": "失败时，有相应测试日志输出",
                        "schema": {
                            "$ref": "#/definitions/controls.ApiErr"
                        }
                    }
                }
            }
        },
        "/pub/internal/token_avgprice": {
            "post": {
                "description": "获取token平均价格共识",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "default"
                ],
                "summary": "获取token平均价格共识:",
                "operationId": "TokenAvgHlPriceHandler",
                "parameters": [
                    {
                        "description": "节点价格列表",
                        "name": "nodePrices",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/services.HLPriceView"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "stock info",
                        "schema": {
                            "$ref": "#/definitions/services.HLPriceView"
                        },
                        "headers": {
                            "sign": {
                                "type": "string",
                                "description": "签名信息"
                            }
                        }
                    },
                    "500": {
                        "description": "失败时，有相应测试日志输出",
                        "schema": {
                            "$ref": "#/definitions/controls.ApiErr"
                        }
                    }
                }
            }
        },
        "/pub/stock/aggre_info/{code}/{data_type}/{timestamp}": {
            "get": {
                "description": "获取共识美股价格 苹果代码  AAPL  ,苹果代码 TSLA",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "default"
                ],
                "summary": "获取共识美股价格:",
                "operationId": "StockAggreHandler",
                "parameters": [
                    {
                        "enum": [
                            "USD",
                            "AAPL",
                            "TSLA"
                        ],
                        "type": "string",
                        "default": "AAPL",
                        "description": "美股代码",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            1,
                            2
                        ],
                        "type": "integer",
                        "default": 1,
                        "description": "最高最低价１最高　２最低价",
                        "name": "data_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1620383144,
                        "description": "unix 秒数",
                        "name": "timestamp",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "stock info list",
                        "schema": {
                            "$ref": "#/definitions/services.StockData"
                        },
                        "headers": {
                            "sign": {
                                "type": "string",
                                "description": "签名信息"
                            }
                        }
                    },
                    "500": {
                        "description": "失败时，有相应测试日志输出",
                        "schema": {
                            "$ref": "#/definitions/controls.ApiErr"
                        }
                    }
                }
            }
        },
        "/pub/stock/any_api": {
            "get": {
                "description": "当前节any-api",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "default"
                ],
                "summary": "当前节点any-api",
                "operationId": "NodeAnyApiHandler",
                "parameters": [
                    {
                        "type": "string",
                        "default": "https://min-api.cryptocompare.com/data/pricemultifull?fsyms=ETH\u0026tsyms=USD",
                        "description": "数据url",
                        "name": "req",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "RAW.ETH.USD.VOLUME24HOUR",
                        "description": "指向数据字段的json path",
                        "name": "path",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "$ref": "#/definitions/controls.AnyApiRes"
                        }
                    },
                    "500": {
                        "description": "失败时，有相应测试日志输出",
                        "schema": {
                            "$ref": "#/definitions/controls.ApiErr"
                        }
                    }
                }
            }
        },
        "/pub/stock/any_apis": {
            "get": {
                "description": "所有节点any-api",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "default"
                ],
                "summary": "所有节点any-api",
                "operationId": "NodeAnyApisHandler",
                "parameters": [
                    {
                        "type": "string",
                        "default": "https://min-api.cryptocompare.com/data/pricemultifull?fsyms=ETH\u0026tsyms=USD",
                        "description": "数据url",
                        "name": "req",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "RAW.ETH.USD.VOLUME24HOUR",
                        "description": "指向数据字段的json path",
                        "name": "path",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "any api data",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controls.AnyApiRes"
                            }
                        }
                    },
                    "500": {
                        "description": "失败时，有相应测试日志输出",
                        "schema": {
                            "$ref": "#/definitions/controls.ApiErr"
                        }
                    }
                }
            }
        },
        "/pub/stock/info": {
            "get": {
                "description": "获取美股价格 苹果代码  AAPL  ,苹果代码 TSLA",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "default"
                ],
                "summary": "获取美股价格:",
                "operationId": "StockInfoHandler",
                "parameters": [
                    {
                        "enum": [
                            "AAPL",
                            "TSLA",
                            "USD"
                        ],
                        "type": "string",
                        "default": "AAPL",
                        "description": "美股代码",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            1,
                            2
                        ],
                        "type": "integer",
                        "default": 1,
                        "description": "最高最低价１最高　２最低价",
                        "name": "data_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1620383144,
                        "description": "unix 秒数",
                        "name": "timestamp",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "stock info",
                        "schema": {
                            "$ref": "#/definitions/services.StockNode"
                        },
                        "headers": {
                            "sign": {
                                "type": "string",
                                "description": "签名信息"
                            }
                        }
                    },
                    "500": {
                        "description": "失败时，有相应测试日志输出",
                        "schema": {
                            "$ref": "#/definitions/controls.ApiErr"
                        }
                    }
                }
            }
        },
        "/pub/stock/market_status/{timestamp}": {
            "get": {
                "description": "获取美股市场开盘状态,支持节假日,夏令时",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "default"
                ],
                "summary": "获取美股市场开盘状态:",
                "operationId": "UsaMarketStatusHandler",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "unix 秒数； 0表示当前时间",
                        "name": "timestamp",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "status",
                        "schema": {
                            "$ref": "#/definitions/controls.resMarketStatus"
                        }
                    },
                    "500": {
                        "description": "失败时，有相应测试日志输出",
                        "schema": {
                            "$ref": "#/definitions/controls.ApiErr"
                        }
                    }
                }
            }
        },
        "/pub/stock/stat": {
            "get": {
                "description": "当前节点状态:记录数,钱包地址",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "default"
                ],
                "summary": "当前节点状态:记录数,钱包地址",
                "operationId": "NodeStatHandler",
                "responses": {
                    "200": {
                        "description": "node stat",
                        "schema": {
                            "$ref": "#/definitions/main.NodeStat"
                        },
                        "headers": {
                            "sign": {
                                "type": "string",
                                "description": "签名信息"
                            }
                        }
                    },
                    "500": {
                        "description": "失败时，有相应测试日志输出",
                        "schema": {
                            "$ref": "#/definitions/controls.ApiErr"
                        }
                    }
                }
            }
        },
        "/pub/stock/stats": {
            "get": {
                "description": "所有节点状态:记录数,钱包地址",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "default"
                ],
                "summary": "所有节点状态:记录数,钱包地址",
                "operationId": "NodeStatsHandler",
                "responses": {
                    "200": {
                        "description": "Node Stat list",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.NodeStat"
                            }
                        }
                    },
                    "500": {
                        "description": "失败时，有相应测试日志输出",
                        "schema": {
                            "$ref": "#/definitions/controls.ApiErr"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controls.AnyApiRes": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "节点取回的数据：取回数据的类型可能为　bool／字符串／数字等；但为了统一签名处理，将取回的数据转换为string，",
                    "type": "string"
                },
                "node": {
                    "description": "节点名",
                    "type": "string"
                },
                "req": {
                    "description": "数据源",
                    "type": "string"
                },
                "sign": {
                    "description": "签名：　hash= keccak256(abi.encodePacked(Req, Data).toEthSignedMessageHash()",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "controls.ApiErr": {
            "type": "object",
            "properties": {
                "Error": {
                    "type": "string"
                }
            }
        },
        "controls.resMarketStatus": {
            "type": "object",
            "properties": {
                "isOpening": {
                    "type": "boolean"
                },
                "openTime": {
                    "type": "integer"
                }
            }
        },
        "main.NodeStat": {
            "type": "object",
            "properties": {
                "blockPricesUpdateAt": {
                    "description": "eth价格信息最后更新时间",
                    "type": "string"
                },
                "cionPricesUpdateAt": {
                    "description": "币价换算信息最后更新时间",
                    "type": "string"
                },
                "node": {
                    "description": "节点名",
                    "type": "string"
                },
                "stockRows": {
                    "description": "股票信息数据库记录数",
                    "type": "integer"
                },
                "stockUpdateAt": {
                    "description": "股票信息最后更新时间",
                    "type": "string"
                },
                "uptime": {
                    "type": "string"
                },
                "walletAddre": {
                    "description": "钱包地址",
                    "type": "string"
                }
            }
        },
        "services.BlockPrice": {
            "type": "object",
            "properties": {
                "blockTime": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "price": {
                    "type": "number"
                }
            }
        },
        "services.CoinPriceView": {
            "type": "object",
            "properties": {
                "bigPrice": {
                    "type": "string"
                },
                "coin": {
                    "description": "目标币价",
                    "type": "string"
                },
                "node": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "sign": {
                    "description": "Sign_Hash值由 Timestamp+Coin+VsCoin+BigPrice计算",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "timestamp": {
                    "type": "integer"
                },
                "vsCoin": {
                    "description": "vs币价",
                    "type": "string"
                }
            }
        },
        "services.HLDataPriceView": {
            "type": "object",
            "properties": {
                "avgSigns": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.HLPriceView"
                    }
                },
                "bigPrice": {
                    "type": "string"
                },
                "code": {
                    "description": "合约代码",
                    "type": "string"
                },
                "dataType": {
                    "description": "最高最低价１最高　２最低价",
                    "type": "integer"
                },
                "priceUsd": {
                    "type": "number"
                },
                "sign": {
                    "description": "Sign_Hash值由 Timestamp，DataType,Code,BigPrice",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "signs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.HLPriceView"
                    }
                },
                "timestamp": {
                    "description": "Node string",
                    "type": "integer"
                }
            }
        },
        "services.HLPriceView": {
            "type": "object",
            "properties": {
                "bigPrice": {
                    "type": "string"
                },
                "code": {
                    "description": "合约代码",
                    "type": "string"
                },
                "dataType": {
                    "description": "最高最低价１最高　２最低价",
                    "type": "integer"
                },
                "node": {
                    "type": "string"
                },
                "nodeAddress": {
                    "type": "string"
                },
                "priceUsd": {
                    "type": "number"
                },
                "sign": {
                    "description": "Sign_Hash值由 Timestamp，DataType,Code,BigPrice",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "services.OneDayStat": {
            "type": "object",
            "properties": {
                "VolumeUsd": {
                    "type": "number"
                },
                "liquidityChange": {
                    "description": "变化百分比",
                    "type": "number"
                },
                "liquidityUsd": {
                    "type": "number"
                },
                "priceChange": {
                    "type": "number"
                },
                "txCount": {
                    "type": "number"
                },
                "txCountChange": {
                    "description": "变化百分比",
                    "type": "number"
                },
                "volumeChange": {
                    "description": "变化百分比",
                    "type": "number"
                }
            }
        },
        "services.PriceView": {
            "type": "object",
            "properties": {
                "bigPrice": {
                    "type": "string"
                },
                "code": {
                    "description": "合约代码",
                    "type": "string"
                },
                "node": {
                    "type": "string"
                },
                "nodeAddress": {
                    "type": "string"
                },
                "priceUsd": {
                    "type": "number"
                },
                "sign": {
                    "description": "Sign_Hash值由 Timestamp,Code,BigPrice",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "services.StockData": {
            "type": "object",
            "properties": {
                "Price": {
                    "description": "平均价",
                    "type": "number"
                },
                "Timestamp": {
                    "description": "unix 秒数",
                    "type": "integer"
                },
                "avgSigns": {
                    "description": "所有节点平均价格签名列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.StockNode"
                    }
                },
                "bigPrice": {
                    "description": "Multiply the Price by 1000000000000000000 to remove decimals",
                    "type": "string"
                },
                "code": {
                    "description": "合约代码",
                    "type": "string"
                },
                "dataType": {
                    "description": "最高最低价１最高　２最低价",
                    "type": "integer"
                },
                "isMarketOpening": {
                    "type": "boolean"
                },
                "marketOpenTime": {
                    "type": "integer"
                },
                "sign": {
                    "description": "计算平均价格的节点的签名　Sign_Hash值由 Timestamp　DataType BigPrice Code计算",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "signs": {
                    "description": "所有节点签名列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.StockNode"
                    }
                },
                "stockCode": {
                    "description": "股票代码",
                    "type": "string"
                }
            }
        },
        "services.StockNode": {
            "type": "object",
            "properties": {
                "Timestamp": {
                    "description": "unix 秒数",
                    "type": "integer"
                },
                "bigPrice": {
                    "description": "Multiply the Price by 1000000000000000000 to remove decimals",
                    "type": "string"
                },
                "code": {
                    "description": "合约代码",
                    "type": "string"
                },
                "dataType": {
                    "description": "最高最低价１最高　２最低价",
                    "type": "integer"
                },
                "node": {
                    "description": "节点名字",
                    "type": "string"
                },
                "nodeAddress": {
                    "description": "节点地址",
                    "type": "string"
                },
                "price": {
                    "description": "新价",
                    "type": "number"
                },
                "sign": {
                    "description": "Sign_Hash值由 Timestamp　DataType BigPrice Code计算",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "stockCode": {
                    "description": "股票代码",
                    "type": "string"
                }
            }
        },
        "services.TokenDayData": {
            "type": "object",
            "properties": {
                "__typename": {
                    "type": "string"
                },
                "dailyVolumeETH": {
                    "type": "string"
                },
                "dailyVolumeToken": {
                    "type": "string"
                },
                "dailyVolumeUSD": {
                    "description": "每天成交量",
                    "type": "string"
                },
                "date": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "priceUSD": {
                    "description": "每天最后一次价格",
                    "type": "string"
                },
                "totalLiquidityETH": {
                    "type": "string"
                },
                "totalLiquidityToken": {
                    "type": "string"
                },
                "totalLiquidityUSD": {
                    "type": "string"
                }
            }
        },
        "services.TokenInfo": {
            "type": "object",
            "properties": {
                "blockTime": {
                    "type": "integer"
                },
                "decimals": {
                    "type": "string"
                },
                "derivedETH": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "oneDayStat": {
                    "description": "最近24小时统计",
                    "$ref": "#/definitions/services.OneDayStat"
                },
                "priceUsd": {
                    "type": "number"
                },
                "symbol": {
                    "type": "string"
                },
                "totalLiquidity": {
                    "type": "string"
                },
                "totalSupply": {
                    "type": "string"
                },
                "tradeVolume": {
                    "type": "string"
                },
                "tradeVolumeUSD": {
                    "type": "string"
                },
                "txCount": {
                    "type": "string"
                },
                "untrackedVolumeUSD": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "stock-info-api",
	Description: "stock-info-api接口文档.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
