basePath: /
definitions:
  main.ApiErr:
    properties:
      Error:
        type: string
    type: object
  main.NodeAddre:
    properties:
      node:
        type: string
      walletAddre:
        type: string
    type: object
  services.StockData:
    properties:
      Price:
        description: 平均价
        type: number
      Timestamp:
        description: unix 秒数
        type: integer
      code:
        type: string
      sign:
        description: 计算平均价格的节点的签名
        items:
          type: integer
        type: array
      signs:
        items:
          $ref: '#/definitions/services.StockNode'
        type: array
    type: object
  services.StockNode:
    properties:
      Timestamp:
        description: unix 秒数
        type: integer
      code:
        type: string
      node:
        description: 节点名字
        type: string
      price:
        description: 新价
        type: number
      sign:
        items:
          type: integer
        type: array
    type: object
info:
  contact:
    email: wuxiaofei@rechaintech.com
    name: 伍晓飞
  description: stock-info-api接口文档.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://rrl360.com/index.html
  title: stock-info-api
  version: "1.0"
paths:
  /pub/stock/aggre_info:
    get:
      consumes:
      - application/json
      description: 获取共识美股价格 苹果代码  AAPL  ,苹果代码 TSLA
      operationId: StockAggreHandler
      parameters:
      - default: AAPL
        description: 美股代码
        in: query
        name: code
        required: true
        type: string
      - default: 1620383144
        description: unix 秒数
        in: query
        name: timestamp
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: stock info
          headers:
            sign:
              description: 签名信息
              type: string
          schema:
            $ref: '#/definitions/services.StockData'
        "500":
          description: 失败时，有相应测试日志输出
          schema:
            $ref: '#/definitions/main.ApiErr'
      summary: '获取共识美股价格:'
      tags:
      - default
  /pub/stock/info:
    get:
      consumes:
      - application/json
      description: 获取美股价格 苹果代码  AAPL  ,苹果代码 TSLA
      operationId: StockInfoHandler
      parameters:
      - default: AAPL
        description: 美股代码
        in: query
        name: code
        required: true
        type: string
      - default: 1620383144
        description: unix 秒数
        in: query
        name: timestamp
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: stock info
          headers:
            sign:
              description: 签名信息
              type: string
          schema:
            $ref: '#/definitions/services.StockNode'
        "500":
          description: 失败时，有相应测试日志输出
          schema:
            $ref: '#/definitions/main.ApiErr'
      summary: '获取美股价格:'
      tags:
      - default
  /pub/stock/node_wallet:
    get:
      consumes:
      - application/json
      description: 当前节点钱包地址
      operationId: NodeWalletAddreHandler
      produces:
      - application/json
      responses:
        "200":
          description: stock info
          headers:
            sign:
              description: 签名信息
              type: string
          schema:
            type: string
        "500":
          description: 失败时，有相应测试日志输出
          schema:
            $ref: '#/definitions/main.ApiErr'
      summary: '当前节点钱包地址:'
      tags:
      - default
  /pub/stock/node_wallets:
    get:
      consumes:
      - application/json
      description: 所有节点钱包地址列表
      operationId: AllWalletAddreHandler
      produces:
      - application/json
      responses:
        "200":
          description: stock info
          schema:
            items:
              $ref: '#/definitions/main.NodeAddre'
            type: array
        "500":
          description: 失败时，有相应测试日志输出
          schema:
            $ref: '#/definitions/main.ApiErr'
      summary: '所有节点钱包地址列表:'
      tags:
      - default
swagger: "2.0"
