basePath: /
definitions:
  main.ApiErr:
    properties:
      Error:
        type: string
    type: object
  main.ApiOk:
    properties:
      Msg:
        example: ok
        type: string
    type: object
  main.VerObj:
    properties:
      data:
        description: 'stockInfo json: {"code":"AAPL","price":128.1,"name":"苹果","timestamp":1620292445,"UpdatedAt":"2021-05-06T17:14:05.878+08:00"}'
        type: object
      sign:
        example: UhRVNsT8B5Za6oO3APH0T9ebPMKHxDDhkscYuILl7lDepDMzyBaQsEu9vwTRIfoYBS8udfEanI/DUAhwnIdFJf9woIv7Oo+OS6q3sF3B5Vx9NN2ipXJ4wjTf2ct7FbS1vXAvTXSmA2svj+LF8P1PIEClITBqu/EWZXTpHvAlbGAAeF+hHO7/FquLHVDavLC+OENyb0CP+NvH+ytZ69tav0DqbGp+NGGil/ImZpPsetbOxwuhC/U1CV6Ap8qgRWe8s6IpOawXDAavLMHUmXVvORDf/XVzaQUJ5ob+vTsSTZwQsvj/4jmsODFt8eKFYL/7vyN/i3HkiDwhq0w85kqHgg==
        format: base64
        type: string
    type: object
  services.StockData:
    properties:
      Price:
        description: 最新价
        type: number
      Timestamp:
        description: unix 秒数
        type: integer
      sign:
        description: 计算平均价格的节点的签名
        type: string
      signs:
        items:
          $ref: '#/definitions/services.StockNode'
        type: array
    type: object
  services.StockNode:
    properties:
      Timestamp:
        description: unix 秒数
        type: integer
      node:
        description: 节点名字
        type: string
      price:
        description: 新价
        type: number
      sign:
        type: string
    type: object
info:
  contact:
    email: wuxiaofei@rechaintech.com
    name: 伍晓飞
  description: stock-info-api接口文档.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://rrl360.com/index.html
  title: stock-info-api
  version: "1.0"
paths:
  /pub/stock/aggre_info:
    get:
      consumes:
      - application/json
      description: 获取共识美股价格 苹果代码  AAPL  ,苹果代码 TSLA
      operationId: StockAggreHandler
      parameters:
      - default: AAPL
        description: 美股代码
        in: query
        name: code
        required: true
        type: string
      - default: 1620383144
        description: unix 秒数
        in: query
        name: timestamp
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: stock info
          headers:
            sign:
              description: 签名信息
              type: string
          schema:
            $ref: '#/definitions/services.StockData'
        "500":
          description: 失败时，有相应测试日志输出
          schema:
            $ref: '#/definitions/main.ApiErr'
      summary: '获取共识美股价格:'
      tags:
      - default
  /pub/stock/info:
    get:
      consumes:
      - application/json
      description: 获取美股价格 苹果代码  AAPL  ,苹果代码 TSLA
      operationId: StockInfoHandler
      parameters:
      - default: AAPL
        description: 美股代码
        in: query
        name: code
        required: true
        type: string
      - default: 1620383144
        description: unix 秒数
        in: query
        name: timestamp
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: stock info
          headers:
            sign:
              description: 签名信息
              type: string
          schema:
            $ref: '#/definitions/services.StockNode'
        "500":
          description: 失败时，有相应测试日志输出
          schema:
            $ref: '#/definitions/main.ApiErr'
      summary: '获取美股价格:'
      tags:
      - default
  /pub/stock/sign_verify:
    post:
      consumes:
      - application/json
      description: 签名验证
      operationId: VerifyInfoHandler
      parameters:
      - description: 需要验证的对象
        in: body
        name: verObj
        required: true
        schema:
          $ref: '#/definitions/main.VerObj'
      produces:
      - application/json
      responses:
        "200":
          description: ok info
          schema:
            $ref: '#/definitions/main.ApiOk'
        "500":
          description: 失败时，有相应测试日志输出
          schema:
            $ref: '#/definitions/main.ApiErr'
      summary: '签名验证:'
      tags:
      - default
swagger: "2.0"
